//Contains all the strings shared among different views
AdminPortalGenericStrConst = {
    qtsLabelText: 'Question',
    qtsTxtboxPlaceholderTxt: 'Add Question...',
    questionIssue: 'Please enter a valid question',
    answerIssue: 'Please enter valid answer',
    successQtsAddMessage: 'Question has been added successfully',
    deleteButtonLabel: 'Delete',
    SaveButtonLabel: 'Save'
};

//Contains all the strings used in Admin Portal page
AdminPortalStrConst = {
    crawlerNotification: 'Crawling of the Website has started.You will be notified by mail when the Crawling completes.'
};

//Contains all the strings used in 'Create Intent' tab
CreateQnaTabStrConst = {
    excelUploadFileSelect: 'The file has %fileName% been selected',
    excelIssue: 'Please upload a valid Excel file!',
    invalidQuestionMessage: 'Please enter a question in the dialog box before adding additional questions.', //Extra space to append question number
    questionDeletedMessage: 'Question Deleted',
    excelUploadMessage: 'Choose a file to upload',
    categoryGeneral: 'general',
    categoryAcronym: 'acronym',
    notApplicable: 'Not applicable'
};

//Contains all the strings used in 'Update Intent' tab
UpdateQnaTabStrConst = {
    editInProgressMessage: "One question set is already being edited",
    enterValidQuestionMessage: "Please enter a valid question",
    autoGeneratedLower: "autogenerated"
};

//Contains all the strings used in 'Unanswered Questions' tab
UnansweredQuestStrConst = {
    // Alerts messages to be added
};

BotPageStrConst = {
    mobiHelpMessage: "Ask MOBI for Help",
    placeHolder: "placeholder",
    askQuesMessage: "Ask a Question...",
    openChatText: "Open to ask MOBI questions",
    closeChat: "Minimize"

};

BotConstants = {
    botId: "User",
    botUserName: "User",
    tokenRefreshValue: 1800,
    sendMessageTitle: "Send",
    countOfLimit: 100
};

RedirectConst = {
    regex1: "^(?:.*[&\\?]",
    regex2: /[\.\+\*]/g,
    regex3: "\\$&",
    regex4: "(?:\\=([^&]*))?)?.*$",
    regex5: "i",
    regex6: "$1",
    keyword: "keyword",
    url: "url"
};